name       : nas
version    : 1.9.5
release    : 2
source     :
    - http://downloads.sourceforge.net/nas/nas-1.9.5.tar.gz : b7884afb38feec03a196bd3b7e9c47b803c830ecd10d7455e9c97e122c37944c
license    : MIT
component  : programming.library
summary    : Network Audio System library
emul32     : yes
description: |
    Network Audio System library
builddeps  :
    - pkgconfig32(xau)
    - pkgconfig32(xaw7)
    - pkgconfig32(xt)
    - pkgconfig32(x11)
    - imake
    - gccmakedep
build      : |
    xmkmf
    %make -j1 World CC="$CC"
install    : |
    %make_install USRLIBDIR=%libdir% CC="$CC"
    rm -v $installdir/%libdir%/*.a
