name       : nas
version    : 1.9.4
release    : 1
source     :
    - http://downloads.sourceforge.net/nas/nas-1.9.4.src.tar.gz : cf36ea63751ce86cfd3b76c1659ce0d6a361a2e7cb34069854e156532703b39d
license    : MIT
component  : programming.library
summary    : Network Audio System library
emul32     : yes
description: |
    Network Audio System library
builddeps  :
    - pkgconfig32(xau)
    - pkgconfig32(xaw7)
    - pkgconfig32(xt)
    - pkgconfig32(x11)
    - imake
    - gccmakedep
build      : |
    xmkmf
    %make -j1 World CC="$CC"
install    : |
    %make_install USRLIBDIR=%libdir% CC="$CC"
    rm -v $installdir/%libdir%/*.a
